language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=3.4.*

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover