language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
- wget http://getcomposer.org/composer.phar
- php -d memory_limit=-1 composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
- php -d memory_limit=-1 composer.phar install --no-interaction $COMPOSER_FLAGS
- phpunit --coverage-text
